name: Template Linux bash

on:
  workflow_call:
    inputs:
      deploy_platform:
        description: "Plataforma de despliegue"
        required: true
        default: "linux"
        type: string
      environment:
        description: "Nombre del entorno GitHub (dev, homo, prod)"
        required: true
        type: string
      sonar_enabled:
        description: "Habilitar análisis SonarQube"
        required: false
        default: true  # <-- Sin comillas, valor booleano directo
        type: boolean  # <-- Tipo definido como boolean

jobs:
  SONAR:
    if: ${{ inputs.environment == 'desarrollo' && inputs.sonar_enabled }} # <-- se evalúa directo como booleano
    uses: PRUEBA-INTERNA-001/chi-GitHub-Functions/.github/workflows/sonarScan.yml@main
    with:
      deploy_platform: ${{ inputs.deploy_platform }}
    secrets: inherit
     
  DEPLOY:
    needs: [SONAR]
    if: ${{ inputs.environment == 'desarrollo' && !inputs.sonar_enabled || needs.SONAR.result == 'success' }}  # <-- Lógica booleana
    uses: PRUEBA-INTERNA-001/chi-GitHub-Functions/.github/workflows/copyRecursiveFileTo.yml@main
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

  CREATE_RELEASE:
    if: ${{ inputs.environment != 'desarrollo' }}
    uses: PRUEBA-INTERNA-001/chi-GitHub-Functions/.github/workflows/createRelease.yml@main
    with:
      environment: ${{ inputs.environment }}
      source_workflow: linuxBash-ci.yml  # <- Nombre del workflow que subió el artifact
    secrets: inherit

