name: Template Linux bash

on:
  workflow_call:
    inputs:
      deploy_platform:
        description: "Plataforma de despliegue"
        required: true
        default: "linux"
        type: string
      environment:
        description: "Nombre del entorno GitHub (dev, homo, prod)"
        required: true
        type: string
      sonar_enabled:
        description: "Habilitar análisis SonarQube"
        required: false
        default: true  # <-- Sin comillas, valor booleano directo
        type: boolean  # <-- Tipo definido como boolean
      path_destino:
        description: 'Path destino donde se copiaran los archivos'
        required: true
        default: '/tmp'
        type: string
      mask_include_files:
        description: "Filtro de carpetas o archivos a copiar a destino"
        required: false
        default: '**/*'
        type: string
      pre_script_type:
        description: "Tipo de script a utilizar sh o bat"
        required: false
        default: 'sh'
        type: string
      pre_script_path:
        description: "Path del script a utilizar sh o bat"
        required: false
        default: 'scripts/preScript.sh'
        type: string
      servidores:
        description: "Servidores donde se copiaran los archivos"
        required: false
        default: ''
        type: string


jobs:   
  DEPLOY:
    uses: PRUEBA-INTERNA-001/chi-GitHub-Functions/.github/workflows/copyRecursiveFileTo.yml@main
    with:
      environment: ${{ inputs.environment }}
      path_destino: ${{ inputs.path_destino }}
      mask_include_files: ${{ inputs.mask_include_files }}
      pre_script_type: ${{ inputs.pre_script_type }}
      pre_script_path: ${{ inputs.pre_script_path }}
      servidores: ${{ inputs.servidores }}
    secrets: inherit

