name: Template Linux bash

on:
  workflow_call:
    inputs:
      deploy_platform:
        description: "Plataforma de despliegue"
        required: true
        default: "linux"
        type: string
      environment:
        description: "Nombre del entorno GitHub (dev, homo, prod)"
        required: true
        type: string
      sonar_enabled:
        description: "Habilitar análisis SonarQube"
        required: false
        default: true  # <-- Sin comillas, valor booleano directo
        type: boolean  # <-- Tipo definido como boolean
      create_release:
        description: "Habilitar la creación del release"
        required: false
        default: false  # <-- Sin comillas, valor booleano directo
        type: boolean  # <-- Tipo definido como boolean

jobs:
  SONAR:
    if: ${{ inputs.sonar_enabled }} # <-- se evalúa directo como booleano
    uses: PRUEBA-INTERNA-001/chi-GitHub-Functions/.github/workflows/sonarScan.yml@main
    with:
      deploy_platform: ${{ inputs.deploy_platform }}
    secrets: inherit
     
  DEPLOY:
    needs: [SONAR]
    uses: PRUEBA-INTERNA-001/chi-GitHub-Functions/.github/workflows/copyRecursiveFileTo.yml@main
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

  CREATE_RELEASE:
    needs: [DEPLOY]
    if: ${{ inputs.create_release }} # se evalúa directo como booleano
    uses: PRUEBA-INTERNA-001/chi-GitHub-Functions/.github/workflows/createRelease.yml@main
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

